### ISSUE TITLE
Kick doesn't work

### ISSUE THREAD

**Issue by erdnaxeli** [Nerdmaster/ruby-irc-yail#12]
I try with two or three arguments (4 arguments raise an exception and kill the bot), but I only got this message :

> I, [2013-02-25T23:39:14.243887 #22488]  INFO -- : Unknown raw 461 from irc.iiens.net: KICK Not enough parameters

There is the code (remove the third argument for the two arguments version) :

``` ruby
@irc.kick(nick, event.channel, nick)
```

Secondly, if I change one of the nick argument to a string, I got a "no such nick/channel" message.

``` ruby
@irc.kick(nick, event.channel, 'test') => Unknown raw 401 from irc.iiens.net: test No such nick/channel
@irc.kick('test', event.channel, nick) => Unknown raw 401 from irc.iiens.net: test No such nick/channel
```

**Comment by Nerdmaster** [comment]
Dang it!  I never actually verified this thing worked, I guess.  I'll try to fix this today.

**Comment by Nerdmaster** [comment]
Just ran a test successfully using YAIL 1.6.1.  YAIL requires 2 parameters, and the third is optional (reason for the kick).  If the server is saying not enough parameters, but YAIL is okay, then one of the parameters might be nil or something.

Can you post the entire function you're using?  Maybe the event you're handling isn't properly setting its channel or something.  (When I explicitly set channel to nil, I get that 461 error)

**Comment by erdnaxeli** [comment]
Oh, sorry, but my argument "nick" was in fact empty. It works fine with goods arguments.

**Comment by Nerdmaster** [comment]
Ah, didn't notice this for a while :)  Thanks for the update!
