### ISSUE TITLE
SSL Connection fails (Nil)

### ISSUE THREAD

**Issue by ayonix** [Nerdmaster/ruby-irc-yail#13]
When I tried to connect to irc.hackint.eu:6697 with SSL it failed with the message:
`net-yail-1.6.1/lib/net/yail/message_parser.rb:68:in `initialize': undefined method `split' for nil:NilClass (NoMethodError)`

**Comment by Nerdmaster** [comment]
I apologize, I lost track of this.  Somehow thought it was only a few days old :(

I'll try to look into it today or tomorrow.  In the meantime, if you could attach a minimal implementation that demonstrates the problem, that would be helpful (otherwise I'll end up building one myself to try and track this down).

Also, did you have success with other versions of YAIL or is this the first version you've tried?

**Comment by ayonix** [comment]
``` ruby
require 'net/yail'

irc = Net::YAIL.new(:address => 'irc.hackint.eu', 
    :port => '6697', 
    :use_ssl => true,
    :username => 'testusername',
    :realname => 'ssltest',
    :nicknames => ['testing_ssl']
    )

irc.start_listening!
```

Did it for me.
Sometimes it worked but in most of the cases it died with the split on Nil.
I haven't tried it with other versions than 1.6.1 though.

**Comment by Nerdmaster** [comment]
The good news is I think I've figured out the problem.  The bad news is it might be a while before I can implement a fix I feel confident in.

**Comment by Nerdmaster** [comment]
Try out 1.6.2 and let me know how it goes :-/

**Comment by ayonix** [comment]
In the beginning I had this error:
`F, [2013-04-10T23:34:10.533268 #16467] FATAL -- : +++ERROR: Unable to open socket connection in Net::YAIL.initialize: #<OpenSSL::SSL::SSLError: SSL    _connect SYSCALL returned=5 errno=0 state=SSLv2/v3 read server hello A>`
I couldn't reproduce it though..so I guess it's not that important and I'll tell you if I get something similar.
Thanks for fixing it :)

**Comment by Nerdmaster** [comment]
Thanks for the update.  Definitely let me know if you hit that error regularly (though it looks like a lower-level error than something YAIL can deal with).
