### ISSUE TITLE
Track users (per channel)

### ISSUE THREAD

**Issue by Nerdmaster** [Nerdmaster/ruby-irc-yail#8]
This would add filters and some terrible magic.  On joining a channel, request a user list.  When anybody parts / quits / joins / etc (other messages?), update user list.

**Comment by erdnaxeli** [comment]
I think this is too much hight level to be done in YAIL. And you can easly do this in your bot.

**Comment by Nerdmaster** [comment]
I think you're probably correct.  I'd like to have this functionality, but maybe a better approach would be building a higher-level bot API in a separate project so that YAIL can stay low-level, but I can still add high-level features.

Thanks for the comment!
