### ISSUE TITLE
:silent doesn't work

### ISSUE THREAD

**Issue by erdnaxeli** [Nerdmaster/ruby-irc-yail#9]
I have all the log with or without :silent.

Futhermore, you say :silent is deprecated, but how can I set the log level without use :silent ?

**Comment by mladoux** [comment]
set :log to equal FATAL.

**Comment by Nerdmaster** [comment]
Yes, :loud and :silent are going to be removed at some point, but for now all they really do is set log levels (where they used to actually control output).

The correct approach would be to do something like `@yail.log.level = Logger::FATAL`.

However, if :silent isn't working, then setting to FATAL won't work, either.  Can you show me a block of code that illustrates the bug?  And can you tell me what you mean by "all the log"?  Are you seeing the debug messages in addition to the normal logging?

**Comment by erdnaxeli** [comment]
By "all the log" I mean the outgoing events (like _(19:12.57) bot: #<Net::YAIL::OutgoingEvent [join]:0x00000000f72a10>_), the notice from the server, the messages received, etc. Maybe it's the normal behaviour, but I don't think all of this is FATAL.

**Comment by Nerdmaster** [comment]
I think I figured this out - you're using IRCBot, which automatically includes the horrible legacy event reporter system.  I'm not sure why I had it do that, other than probably backward compatibility.

The easiest fix is probably to override a method in your IRCBot subclass:

``` ruby
  # Creates the socket connection and registers the (very simple) default
  # welcome handler.  Subclasses should build their hooks in
  # add_custom_handlers to allow auto-creation in case of a restart.
  def connect_socket
    @irc = Net::YAIL.new(@options)

    # THIS is the problem:
    # setup_reporting(@irc)

    # Simple hook for welcome to allow auto-joining of the channel
    @irc.on_welcome self.method(:welcome)

    add_custom_handlers
  end
```

Obviously this is far from ideal as you never know when I may change that method, but it'll get your subclass doing what it needs to without the excessive reporting.

The reporting system is very different from the logger, and I thought I had dropped it entirely, but I guess not :(

Anyway, I'll have to put in a real fix sometime.  Not sure when.

**Comment by erdnaxeli** [comment]
Ok it works, thanks. But I think you need effectively a real fix ;-)

**Comment by Nerdmaster** [comment]
Yeah, I'm going to leave this open to remind myself.  I think the quick fix is going to be adding a check on log level, but longer-term I'll have to do something much smarter.

**Comment by Nerdmaster** [comment]
Forgot to mention this was fixed a while ago.  I'll have to do a real release, but the latest code in the develop branch should have smarter logging.
